### ISSUE TITLE
Works perfectly - Note for those who've already installed xiaoxiaoflood userChromeJS protocol

### ISSUE THREAD

**Issue by Cade66** [earthlng/aboutconfig#1]
I already have xiaoxiaoflood's usrChromeJS 'protocol' installed so the only required step in this case is to add the _aboutconfig_ folder to the user's profile/chrome/_utils_ folder. For whom may be concerned ...
Nice to get back that old about;config format. Nice work, appreciated. Thanks @earthlng

**Comment by LOuroboros** [comment]
I wanted to show some appreciation as well.

I prefer it much more than the current design Firefox uses. I hate this stupid trend of wasting screen space for no reason at all instead of filling it with the actually useful and relevant content instead, which is exactly what Firefox's current about:config design does, so thank you very very much for porting the old about:config @earthlng!

**Comment by earthlng** [comment]
Thanks guys, but really all the credit goes to @xiaoxiaoflood for doing all the hard work like finding the right functions and stuff to register a custom manifest, etc. I merely stripped it down to the bare minimum for people (like myself) who just want the about:config part. So yeah, thanks @xiaoxiaoflood ! Great work and very much appreciated! 👍
