### ISSUE TITLE
Remove Services.jsm import

### ISSUE THREAD

**Issue by aminomancer** [earthlng/aboutconfig#9]
Services.jsm has been removed so I think your script will throw when it tries to import it. It should be fine to remove the import since it's in the global object for privileged page scripts. Cheers!

https://bugzilla.mozilla.org/show_bug.cgi?id=1780695

**Comment by earthlng** [comment]
Thanks! I'll have to check how ESR behaves

**Comment by aminomancer** [comment]
Current ESR is 115, Services.jsm was removed in 117. So this isn't gonna throw in ESR. But you shouldn't need to import Services directly in any recent version. It's a global variable in the parent process. But if you want to be extra cautious, you can do something like this

```js
const Services = window.Services || ChromeUtils.import("resource://gre/modules/Services.jsm").Services;
```

**Comment by earthlng** [comment]
hi,

ESR102 is also still supported for another month, give or take.
But yeah, something like that is what I had in mind. The mozilla guys are using `globalThis` instead of `window` in their own code:

https://searchfox.org/mozilla-central/source/browser/extensions/webcompat/about-compat/aboutPage.js#10

```js
const Services = globalThis.Services || ChromeUtils.import("resource://gre/modules/Services.jsm").Services;
```

not sure what exactly the difference is.

I'll test it in ESR115 and FF117 and then commit a change

thx

**Comment by aminomancer** [comment]
globalThis will work too. It's intended for cross-compatibility with code written for Node.js. But that's WebExtensions code. There isn't any need to use it for a Firefox system page.

**Comment by earthlng** [comment]
ah okay, thanks for clarifying that 👍

**Comment by earthlng** [comment]
I decided to just comment-out the import line, since that works in all recent and current versions incl. ESR155.

Thanks again for your input, @aminomancer !
